#!/usr/bin/env bash

# Bash script to display visitor IP along with HTTP status code from Apache log file

# Use awk to extract and format IP and HTTP status code
awk '{print $1, $9}' apache-access.log
