#!/usr/bin/env bash

# Bash script to group visitors by IP and HTTP status code, and display data

# Use awk to extract and format IP and HTTP status code, count occurrences, and sort
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
